config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :attachments

  validates :customer_name, presence: true
  validates :sales_office, presence: true
  validates :sales_representative, presence: true
  validates :request_type, presence: true
  validates :request_content, presence: true
  validates :order_date, presence: true
  validates :due_date, presence: true
  validates :revenue, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cost, presence: true, numericality: { greater_than_or_equal_to: 0 }

  REQUEST_TYPES = { 新規依頼: 0, 修正依頼: 1, 追加依頼: 2, バグ修正: 3, その他: 4 }
  REQUEST_CONTENTS = { WEBアプリ制作: 0, WEBデザイン制作: 1, スマホアプリ制作: 2, システム構築: 3, データ解析: 4, その他: 5 }

  # クラスメソッドとして定義
  def self.request_types
    REQUEST_TYPES
  end

  def self.request_contents
    REQUEST_CONTENTS
  end

  before_save :calculate_profit

  private

  def calculate_profit
    self.profit = self.revenue.to_i - self.cost.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Originalapp42189</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1 class="text-center">案件一覧</h1>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>顧客名</th>
      <th>営業拠点</th>
      <th>営業担当</th>
      <th>依頼区分</th>
      <th>依頼内容</th>
      <th>受注日</th>
      <th>納期</th>
      <th>売上</th>
      <th>コスト</th>
      <th>利益</th>
      <th>添付資料</th>
      <th>備考</th>
    </tr>
  </thead>
  <tbody>
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <tr ondblclick="location.href='<%= project_path(project) %>'" style="cursor: pointer;">
          <td><%= project.customer_name %></td>
          <td><%= project.sales_office %></td>
          <td><%= project.sales_representative %></td>
          <td><%= Project.request_types[project.request_type] %></td>
          <td><%= Project.request_contents[project.request_content] %></td>
          <td><%= project.order_date %></td>
          <td><%= project.due_date %></td>
          <td><%= project.revenue %></td>
          <td><%= project.cost %></td>
          <td><%= project.profit %></td>
          <td>
            <% project.attachments.each do |attachment| %>
              <%= link_to attachment.filename, url_for(attachment), target: "_blank" %><br>
            <% end %>
          </td>
          <td><%= project.remarks %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="12" class="text-center">現在、案件が登録されていません。</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center mt-4">
  <%= link_to "【新規登録】", new_project_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>